// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc39oNyW2-cOx4vmkamgHD4gaKv3jcrxE',
    appId: '1:480032415771:web:6bc5795efbf9ab316618be',
    messagingSenderId: '480032415771',
    projectId: 'qr-code-18c7b',
    authDomain: 'qr-code-18c7b.firebaseapp.com',
    storageBucket: 'qr-code-18c7b.appspot.com',
    measurementId: 'G-10YWPC8V4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCk-R3w3Og99Z2khY1mQeKeLwdGHqg8WI',
    appId: '1:480032415771:android:545dc8ef044cfcac6618be',
    messagingSenderId: '480032415771',
    projectId: 'qr-code-18c7b',
    storageBucket: 'qr-code-18c7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClLKCESAgmBrkEDGXJh8hfa7pPh_ev9QU',
    appId: '1:480032415771:ios:9314621e55fa3c046618be',
    messagingSenderId: '480032415771',
    projectId: 'qr-code-18c7b',
    storageBucket: 'qr-code-18c7b.appspot.com',
    iosClientId: '480032415771-tje4jqrfe7dbu3h5eq00dkp69bjjlgnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClLKCESAgmBrkEDGXJh8hfa7pPh_ev9QU',
    appId: '1:480032415771:ios:9314621e55fa3c046618be',
    messagingSenderId: '480032415771',
    projectId: 'qr-code-18c7b',
    storageBucket: 'qr-code-18c7b.appspot.com',
    iosClientId: '480032415771-tje4jqrfe7dbu3h5eq00dkp69bjjlgnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrCode',
  );
}
